export enum ControlCommand {
  dockStart = 'dock',
  undockStart = 'undock',
  chargeTrigger = 'chargeTrigger',
  randomSeq = 'randomSeq',
  ledControl = 'ledControl',
  lidarOnOff = 'lidarOnOff',
  pathOnOff = 'pathOnOff',
  motorOnOff = 'motorOnOff',
  safetyFieldControl = 'safetyFieldControl',
  setSafetyField = 'setSafetyField',
  getSafetyField = 'getSafetyField',
  getSafetyFlag = 'getSafetyFlag',
  setSafetyFlag = 'setSafetyFlag',
  footMove = 'footMove',
  footStop = 'footStop',
  getDigitalIO = 'getDigitalIO',
  setDigitalIO = 'setDigitalIO',
  setObsBox = 'setObsBox',
  getObsBox = 'getObsBox',
}

export enum DetectCommand {
  aruco = 'aruco',
}
export enum LEDColor {
  none = 'none',
  red = 'red',
  blue = 'blue',
  white = 'white',
  green = 'green',
  magenta = 'magenta',
  yellow = 'yellow',
  red_blink = 'red blink',
  blue_blink = 'blue blink',
  white_blink = 'white blink',
  green_blink = 'green blink',
  magenta_blink = 'magenta blink',
  yellow_blink = 'yellow blink',
  unknown = 'unknown',
}
