export const AUTH_SERVICE = 'AUTH_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
export const PERMISSION_SERVICE = 'PERMISSION_SERVICE';
export const ROLE_SERVICE = 'ROLE_SERVICE';
export const GROUP_SERVICE = 'GROUP_SERVICE';
export const AMR_SERVICE = 'AMR_SERVICE';

export const CONFIG_SERVICE = 'CONFIG_SERVICE';
export const CONTROL_SERVICE = 'CONTROL_SERVICE';
export const SETTING_SERVICE = 'SETTING_SERVICE';
export const SLAMNAV_SERVICE = 'SLAMNAV_SERVICE';
export const MOVE_SERVICE = 'MOVE_SERVICE';
export const LOCALIZATION_SERVICE = 'LOCALIZATION_SERVICE';
export const NETWORK_SERVICE = 'NETWORK_SERVICE';

export const FILE_SERVICE = 'FILE_SERVICE';
export const LOG_SERVICE = 'LOG_SERVICE';
export const MAP_SERVICE = 'MAP_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const HOST_SERVER = 'HOST_SERVER';

export const REDIS_SERVICE = 'REDIS_SERVICE';

export const SOCKETIO_SERVICE = 'SOCKETIO_SERVICE';

export const EXTERNAL_ACCESSORY_SERVICE = 'EXTERNAL_ACCESSORY_SERVICE';
export const SOUND_SERVICE = 'SOUND_SERVICE';
export const MQTT_BROKER = 'MQTT_BROKER';

export const TASK_SERVICE = 'TASK_SERVICE';

export const CODE_SERVICE = 'CODE_SERVICE';

export const COBOT_SERVICE = 'COBOT_SERVICE';

export const TCP_SERVICE = 'TCP_SERVICE';
