// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.4
//   protoc               v6.30.2
// source: robot.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "robot";

export interface ReadRobotRequest {
  robotSerial?: string | undefined;
  robotType?: string | undefined;
  robotName?: string | undefined;
  robotIpAddress?: string | undefined;
  robotUri?: string | undefined;
  robotApproveYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface ReadRobotListRequest {
  pageNo?: number | undefined;
  pageSize?: number | undefined;
  searchType?: string | undefined;
  searchText?: string | undefined;
  robotSerial?: string | undefined;
  robotType?: string | undefined;
  robotName?: string | undefined;
  robotIpAddress?: string | undefined;
  robotUri?: string | undefined;
  robotApproveYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdAtStart?: string | undefined;
  createdAtEnd?: string | undefined;
  updatedAtStart?: string | undefined;
  updatedAtEnd?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface ReadRobotResponse {
  robotSerial?: string | undefined;
  robotType?: string | undefined;
  robotName?: string | undefined;
  robotIpAddress?: string | undefined;
  robotUri?: string | undefined;
  robotApproveYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface ReadRobotListResponse {
  pageNo: number;
  pageSize: number;
  totalCount: number;
  totalPage: number;
  searchType?: string | undefined;
  searchText?: string | undefined;
  createdAtStart?: string | undefined;
  createdAtEnd?: string | undefined;
  updatedAtStart?: string | undefined;
  updatedAtEnd?: string | undefined;
  data: ReadRobotListResponse_Robot[];
}

export interface ReadRobotListResponse_Robot {
  robotSerial: string;
  robotType: string;
  robotName: string;
  robotIpAddress: string;
  robotUri: string;
  robotApproveYn: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}

export interface CreateRobotRequest {
  robotSerial: string;
  robotType: string;
  robotName: string;
  robotIpAddress?: string | undefined;
  robotUri?: string | undefined;
  robotApproveYn: string;
  createdAt: string;
  createdBy?: string | undefined;
}

export interface CreateRobotResponse {
  robotSerial: string;
  robotType: string;
  robotName: string;
  robotIpAddress: string;
  robotUri: string;
  robotApproveYn: string;
  createdAt: string;
  createdBy: string;
}

export interface UpdateRobotRequest {
  robotSerial: string;
  data?: UpdateRobotRequest_Robot | undefined;
}

export interface UpdateRobotRequest_Robot {
  robotSerial?: string | undefined;
  robotType?: string | undefined;
  robotName?: string | undefined;
  robotIpAddress?: string | undefined;
  robotUri?: string | undefined;
  robotApproveYn?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
}

export interface UpdateRobotResponse {
  robotSerial: string;
  robotType: string;
  robotName: string;
  robotIpAddress: string;
  robotUri: string;
  robotApproveYn: string;
  updatedAt: string;
  updatedBy: string;
}

export interface DeleteRobotRequest {
  robotSerial: string;
}

export interface DeleteRobotResponse {
  robotSerial: string;
  robotType: string;
  robotName: string;
  robotIpAddress: string;
  robotUri: string;
  robotApproveYn: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}

export const ROBOT_PACKAGE_NAME = "robot";

export interface RobotGrpcServiceClient {
  readRobotList(request: ReadRobotListRequest, metadata?: Metadata): Observable<ReadRobotListResponse>;

  readRobot(request: ReadRobotRequest, metadata?: Metadata): Observable<ReadRobotResponse>;

  createRobot(request: CreateRobotRequest, metadata?: Metadata): Observable<CreateRobotResponse>;

  updateRobot(request: UpdateRobotRequest, metadata?: Metadata): Observable<UpdateRobotResponse>;

  deleteRobot(request: DeleteRobotRequest, metadata?: Metadata): Observable<DeleteRobotResponse>;
}

export interface RobotGrpcServiceController {
  readRobotList(
    request: ReadRobotListRequest,
    metadata?: Metadata,
  ): Promise<ReadRobotListResponse> | Observable<ReadRobotListResponse> | ReadRobotListResponse;

  readRobot(
    request: ReadRobotRequest,
    metadata?: Metadata,
  ): Promise<ReadRobotResponse> | Observable<ReadRobotResponse> | ReadRobotResponse;

  createRobot(
    request: CreateRobotRequest,
    metadata?: Metadata,
  ): Promise<CreateRobotResponse> | Observable<CreateRobotResponse> | CreateRobotResponse;

  updateRobot(
    request: UpdateRobotRequest,
    metadata?: Metadata,
  ): Promise<UpdateRobotResponse> | Observable<UpdateRobotResponse> | UpdateRobotResponse;

  deleteRobot(
    request: DeleteRobotRequest,
    metadata?: Metadata,
  ): Promise<DeleteRobotResponse> | Observable<DeleteRobotResponse> | DeleteRobotResponse;
}

export function RobotGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["readRobotList", "readRobot", "createRobot", "updateRobot", "deleteRobot"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RobotGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RobotGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ROBOT_GRPC_SERVICE_NAME = "RobotGrpcService";
