// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.4
//   protoc               v3.12.4
// source: setting.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "setting";

export interface Empty {
}

export interface GetTypeResponse {
  model: string;
  type: string;
}

export interface SettingRequest {
  type: string;
  data?: string | undefined;
}

export interface SaveSettingRequest {
  type: string;
  key: string;
  value: string;
}

export interface SaveSettingResponse {
  type: string;
  key: string;
  value: string;
}

export interface SettingResponse {
  type: string;
  data?: string | undefined;
}

export interface PresetListRequest {
  type: string;
}

export interface PresetListResponse {
  type: string;
  list: string[];
}

export interface PresetRequest {
  type: string;
  preset: string;
  data?: string | undefined;
}

export interface PresetResponse {
  type: string;
  preset: string;
  data?: string | undefined;
}

export interface GetCameraInfoResponse {
  cam1?: string | undefined;
  cam2?: string | undefined;
}

export interface SetCameraOrderRequest {
  cam1?: string | undefined;
  cam2?: string | undefined;
}

export interface SetCameraOrderResponse {
  cam1?: string | undefined;
  cam2?: string | undefined;
}

export interface PduParam {
  name: string;
  value: string;
  type: string;
}

export interface SetPduParamRequest {
  params: PduParam[];
}

export interface GetPduParamResponse {
  params: PduParam[];
  result?: string | undefined;
  message?: string | undefined;
}

export const SETTING_PACKAGE_NAME = "setting";

export interface SettingGrpcServiceClient {
  getType(request: Empty, metadata?: Metadata): Observable<GetTypeResponse>;

  getSetting(request: SettingRequest, metadata?: Metadata): Observable<SettingResponse>;

  saveSetting(request: SaveSettingRequest, metadata?: Metadata): Observable<SaveSettingResponse>;

  saveSettingAll(request: SettingRequest, metadata?: Metadata): Observable<SettingResponse>;

  /**  */

  getPresetList(request: PresetListRequest, metadata?: Metadata): Observable<PresetListResponse>;

  getPreset(request: PresetRequest, metadata?: Metadata): Observable<PresetResponse>;

  createPreset(request: PresetRequest, metadata?: Metadata): Observable<PresetResponse>;

  deletePreset(request: PresetRequest, metadata?: Metadata): Observable<PresetResponse>;

  savePreset(request: PresetRequest, metadata?: Metadata): Observable<PresetResponse>;

  /** cam */

  getCameraInfo(request: Empty, metadata?: Metadata): Observable<GetCameraInfoResponse>;

  setCameraOrder(request: SetCameraOrderRequest, metadata?: Metadata): Observable<SetCameraOrderResponse>;

  /** pdu */

  getPduParam(request: Empty, metadata?: Metadata): Observable<GetPduParamResponse>;

  setPduParam(request: SetPduParamRequest, metadata?: Metadata): Observable<GetPduParamResponse>;

  getPduDriveParam(request: Empty, metadata?: Metadata): Observable<GetPduParamResponse>;
}

export interface SettingGrpcServiceController {
  getType(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetTypeResponse> | Observable<GetTypeResponse> | GetTypeResponse;

  getSetting(
    request: SettingRequest,
    metadata?: Metadata,
  ): Promise<SettingResponse> | Observable<SettingResponse> | SettingResponse;

  saveSetting(
    request: SaveSettingRequest,
    metadata?: Metadata,
  ): Promise<SaveSettingResponse> | Observable<SaveSettingResponse> | SaveSettingResponse;

  saveSettingAll(
    request: SettingRequest,
    metadata?: Metadata,
  ): Promise<SettingResponse> | Observable<SettingResponse> | SettingResponse;

  /**  */

  getPresetList(
    request: PresetListRequest,
    metadata?: Metadata,
  ): Promise<PresetListResponse> | Observable<PresetListResponse> | PresetListResponse;

  getPreset(
    request: PresetRequest,
    metadata?: Metadata,
  ): Promise<PresetResponse> | Observable<PresetResponse> | PresetResponse;

  createPreset(
    request: PresetRequest,
    metadata?: Metadata,
  ): Promise<PresetResponse> | Observable<PresetResponse> | PresetResponse;

  deletePreset(
    request: PresetRequest,
    metadata?: Metadata,
  ): Promise<PresetResponse> | Observable<PresetResponse> | PresetResponse;

  savePreset(
    request: PresetRequest,
    metadata?: Metadata,
  ): Promise<PresetResponse> | Observable<PresetResponse> | PresetResponse;

  /** cam */

  getCameraInfo(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetCameraInfoResponse> | Observable<GetCameraInfoResponse> | GetCameraInfoResponse;

  setCameraOrder(
    request: SetCameraOrderRequest,
    metadata?: Metadata,
  ): Promise<SetCameraOrderResponse> | Observable<SetCameraOrderResponse> | SetCameraOrderResponse;

  /** pdu */

  getPduParam(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetPduParamResponse> | Observable<GetPduParamResponse> | GetPduParamResponse;

  setPduParam(
    request: SetPduParamRequest,
    metadata?: Metadata,
  ): Promise<GetPduParamResponse> | Observable<GetPduParamResponse> | GetPduParamResponse;

  getPduDriveParam(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetPduParamResponse> | Observable<GetPduParamResponse> | GetPduParamResponse;
}

export function SettingGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getType",
      "getSetting",
      "saveSetting",
      "saveSettingAll",
      "getPresetList",
      "getPreset",
      "createPreset",
      "deletePreset",
      "savePreset",
      "getCameraInfo",
      "setCameraOrder",
      "getPduParam",
      "setPduParam",
      "getPduDriveParam",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SettingGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SettingGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SETTING_GRPC_SERVICE_NAME = "SettingGrpcService";
