// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.4
//   protoc               v3.12.4
// source: code.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "code";

export interface ReadCodeListRequest {
  pageNo?: number | undefined;
  pageSize?: number | undefined;
  searchType?: string | undefined;
  searchText?: string | undefined;
  codeId?: string | undefined;
  code?: string | undefined;
  codeName?: string | undefined;
  codeDesc?: string | undefined;
  parentCode?: string | undefined;
  sortOrder?: number | undefined;
  useYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdAtStart?: string | undefined;
  createdAtEnd?: string | undefined;
  updatedAtStart?: string | undefined;
  updatedAtEnd?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface ReadCodeRequest {
  codeId?: string | undefined;
  code?: string | undefined;
  codeName?: string | undefined;
  codeDesc?: string | undefined;
  parentCode?: string | undefined;
  sortOrder?: number | undefined;
  useYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface CreateCodeRequest {
  codeId: string;
  code: string;
  codeName?: string | undefined;
  codeDesc?: string | undefined;
  parentCode?: string | undefined;
  sortOrder?: number | undefined;
  useYn: string;
  createdAt: string;
  createdBy?: string | undefined;
}

export interface UpdateCodeRequest {
  codeId: string;
  data?: UpdateCodeRequest_Code | undefined;
}

export interface UpdateCodeRequest_Code {
  codeId?: string | undefined;
  code?: string | undefined;
  codeName?: string | undefined;
  codeDesc?: string | undefined;
  parentCode?: string | undefined;
  sortOrder?: number | undefined;
  useYn?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
}

export interface DeleteCodeRequest {
  codeId: string;
}

export interface ReadCodeListResponse {
  pageNo: number;
  pageSize: number;
  totalCount: number;
  totalPage: number;
  searchType?: string | undefined;
  searchText?: string | undefined;
  createdAtStart?: string | undefined;
  createdAtEnd?: string | undefined;
  updatedAtStart?: string | undefined;
  updatedAtEnd?: string | undefined;
  data: ReadCodeListResponse_Code[];
}

export interface ReadCodeListResponse_Code {
  codeId: string;
  code: string;
  codeName: string;
  codeDesc: string;
  parentCode: string;
  sortOrder: number;
  useYn: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}

export interface ReadCodeResponse {
  codeId?: string | undefined;
  code?: string | undefined;
  codeName?: string | undefined;
  codeDesc?: string | undefined;
  parentCode?: string | undefined;
  sortOrder?: number | undefined;
  useYn?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  createdBy?: string | undefined;
  updatedBy?: string | undefined;
}

export interface CreateCodeResponse {
  codeId: string;
  code: string;
  codeName: string;
  codeDesc: string;
  parentCode: string;
  sortOrder: number;
  useYn: string;
  createdAt: string;
  createdBy: string;
}

export interface UpdateCodeResponse {
  codeId: string;
  code: string;
  codeName: string;
  codeDesc: string;
  parentCode: string;
  sortOrder: number;
  useYn: string;
  updatedAt: string;
  updatedBy: string;
}

export interface DeleteCodeResponse {
  codeId: string;
  code: string;
  codeName: string;
  codeDesc: string;
  parentCode: string;
  sortOrder: number;
  useYn: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}

export const CODE_PACKAGE_NAME = "code";

export interface CodeGrpcServiceClient {
  readCodeList(request: ReadCodeListRequest, metadata?: Metadata): Observable<ReadCodeListResponse>;

  readCode(request: ReadCodeRequest, metadata?: Metadata): Observable<ReadCodeResponse>;

  createCode(request: CreateCodeRequest, metadata?: Metadata): Observable<CreateCodeResponse>;

  updateCode(request: UpdateCodeRequest, metadata?: Metadata): Observable<UpdateCodeResponse>;

  deleteCode(request: DeleteCodeRequest, metadata?: Metadata): Observable<DeleteCodeResponse>;
}

export interface CodeGrpcServiceController {
  readCodeList(
    request: ReadCodeListRequest,
    metadata?: Metadata,
  ): Promise<ReadCodeListResponse> | Observable<ReadCodeListResponse> | ReadCodeListResponse;

  readCode(
    request: ReadCodeRequest,
    metadata?: Metadata,
  ): Promise<ReadCodeResponse> | Observable<ReadCodeResponse> | ReadCodeResponse;

  createCode(
    request: CreateCodeRequest,
    metadata?: Metadata,
  ): Promise<CreateCodeResponse> | Observable<CreateCodeResponse> | CreateCodeResponse;

  updateCode(
    request: UpdateCodeRequest,
    metadata?: Metadata,
  ): Promise<UpdateCodeResponse> | Observable<UpdateCodeResponse> | UpdateCodeResponse;

  deleteCode(
    request: DeleteCodeRequest,
    metadata?: Metadata,
  ): Promise<DeleteCodeResponse> | Observable<DeleteCodeResponse> | DeleteCodeResponse;
}

export function CodeGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["readCodeList", "readCode", "createCode", "updateCode", "deleteCode"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CodeGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CodeGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CODE_GRPC_SERVICE_NAME = "CodeGrpcService";
