// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.4
//   protoc               v3.12.4
// source: test.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "test";

export interface TestResult {
  id: string;
  testRecordId: string;
  subject: string;
  result: string;
  testAt: string;
}

export interface TestRecord {
  id: string;
  tester: string;
  tests: TestResult[];
  createdAt: string;
  updatedAt: string;
}

export interface GetTestRecordAllRequest {
  pageNo?: number | undefined;
  pageSize?: number | undefined;
  searchText?: string | undefined;
  searchType?: string | undefined;
  sortOption?: string | undefined;
  sortDirection?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
}

export interface GetTestRecordAllResponse {
  list: TestRecord[];
  pageSize?: number | undefined;
  totalCount?: number | undefined;
  totalPage?: number | undefined;
}

export interface GetTestRecordRequest {
  id: string;
}

export interface GetTestResultRecentRequest {
  subjects: string[];
}

export interface GetTestResultResponse {
  items: TestResult[];
}

export interface GetTestResultbySubjectRequest {
  subject: string;
}

export interface CheckTestRunningRequest {
  sessionId: string;
}

export interface CheckTestRunningResponse {
  isRunning: boolean;
  testRecordId?: string | undefined;
  tester?: string | undefined;
  testSessionId?: string | undefined;
  testEndTimestamp?: number | undefined;
}

export interface StartTestRequest {
  testRecordId: string;
  tester: string;
  sessionId: string;
}

export interface StartTestResponse {
  testRecordId: string;
  tester: string;
  testSessionId: string;
  testEndTimestamp: number;
}

export interface StopTestRequest {
  sessionId: string;
}

export interface StopTestResponse {
  testRecordId?: string | undefined;
  tester?: string | undefined;
  testSessionId?: string | undefined;
}

export interface CreateTestRecordRequest {
  sessionId: string;
  subjects: string[];
  tester?: string | undefined;
}

export interface UpdateTestRecordRequest {
  sessionId: string;
  id: string;
  tester?: string | undefined;
}

export interface UpdateTestResultRequest {
  sessionId: string;
  testRecordId: string;
  subject: string;
  result: string;
}

export const TEST_PACKAGE_NAME = "test";

export interface TestGrpcServiceClient {
  getTestRecordAll(request: GetTestRecordAllRequest, metadata?: Metadata): Observable<GetTestRecordAllResponse>;

  getTestRecord(request: GetTestRecordRequest, metadata?: Metadata): Observable<TestRecord>;

  getTestResultRecent(request: GetTestResultRecentRequest, metadata?: Metadata): Observable<GetTestResultResponse>;

  getTestResultbySubject(
    request: GetTestResultbySubjectRequest,
    metadata?: Metadata,
  ): Observable<GetTestResultResponse>;

  checkTestRunning(request: CheckTestRunningRequest, metadata?: Metadata): Observable<CheckTestRunningResponse>;

  startTest(request: StartTestRequest, metadata?: Metadata): Observable<StartTestResponse>;

  stopTest(request: StopTestRequest, metadata?: Metadata): Observable<StopTestResponse>;

  createTestRecord(request: CreateTestRecordRequest, metadata?: Metadata): Observable<TestRecord>;

  updateTestRecord(request: UpdateTestRecordRequest, metadata?: Metadata): Observable<TestRecord>;

  updateTestResult(request: UpdateTestResultRequest, metadata?: Metadata): Observable<TestResult>;
}

export interface TestGrpcServiceController {
  getTestRecordAll(
    request: GetTestRecordAllRequest,
    metadata?: Metadata,
  ): Promise<GetTestRecordAllResponse> | Observable<GetTestRecordAllResponse> | GetTestRecordAllResponse;

  getTestRecord(
    request: GetTestRecordRequest,
    metadata?: Metadata,
  ): Promise<TestRecord> | Observable<TestRecord> | TestRecord;

  getTestResultRecent(
    request: GetTestResultRecentRequest,
    metadata?: Metadata,
  ): Promise<GetTestResultResponse> | Observable<GetTestResultResponse> | GetTestResultResponse;

  getTestResultbySubject(
    request: GetTestResultbySubjectRequest,
    metadata?: Metadata,
  ): Promise<GetTestResultResponse> | Observable<GetTestResultResponse> | GetTestResultResponse;

  checkTestRunning(
    request: CheckTestRunningRequest,
    metadata?: Metadata,
  ): Promise<CheckTestRunningResponse> | Observable<CheckTestRunningResponse> | CheckTestRunningResponse;

  startTest(
    request: StartTestRequest,
    metadata?: Metadata,
  ): Promise<StartTestResponse> | Observable<StartTestResponse> | StartTestResponse;

  stopTest(
    request: StopTestRequest,
    metadata?: Metadata,
  ): Promise<StopTestResponse> | Observable<StopTestResponse> | StopTestResponse;

  createTestRecord(
    request: CreateTestRecordRequest,
    metadata?: Metadata,
  ): Promise<TestRecord> | Observable<TestRecord> | TestRecord;

  updateTestRecord(
    request: UpdateTestRecordRequest,
    metadata?: Metadata,
  ): Promise<TestRecord> | Observable<TestRecord> | TestRecord;

  updateTestResult(
    request: UpdateTestResultRequest,
    metadata?: Metadata,
  ): Promise<TestResult> | Observable<TestResult> | TestResult;
}

export function TestGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getTestRecordAll",
      "getTestRecord",
      "getTestResultRecent",
      "getTestResultbySubject",
      "checkTestRunning",
      "startTest",
      "stopTest",
      "createTestRecord",
      "updateTestRecord",
      "updateTestResult",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TestGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TestGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TEST_GRPC_SERVICE_NAME = "TestGrpcService";
